# Generated by Django 3.2.19 on 2023-06-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("SALES", "SALES"), ("SUPPORT", "SUPPORT"), ("MANAGEMENT", "MANAGEMENT")],
                default=("SUPPORT", "SUPPORT"),
                max_length=10,
            ),
        ),
    ]
