# Generated by Django 3.2.19 on 2023-05-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SALES', 'sales'), ('SUPPORT', 'support'), ('MANAGEMENT', 'management')], default=('MANAGEMENT', 'management'), max_length=10),
        ),
    ]
