# Generated by Django 3.2.19 on 2023-05-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Updated_Date'),
        ),
    ]
