# Generated by Django 3.2.19 on 2023-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated_Date'),
        ),
    ]
